client_config_backend: settings
client_config:
  client_id: 50526886082-6ov72672edbi6bqnpe75oglm07gn9pdh.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install